// <auto-generated />
using System;
using Test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Test.Migrations
{
    [DbContext(typeof(RequestContext))]
    [Migration("20211001083927_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.RequestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QueryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestLocalTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Test.Models.RequestData", b =>
                {
                    b.OwnsOne("Test.Models.UserStatisticData", "UserData", b1 =>
                        {
                            b1.Property<int>("RequestDataId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("TimeFrom")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("TimeTo")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RequestDataId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("RequestDataId");
                        });

                    b.Navigation("UserData");
                });
#pragma warning restore 612, 618
        }
    }
}
